# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\UC\EPA\SWMM2PEST\SWMM2PEST\UI_Files\SecondPage.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(771, 516)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/EPA1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabOuter = QtWidgets.QTabWidget(self.centralwidget)
        self.tabOuter.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabOuter.setObjectName("tabOuter")
        self.tabParameters = QtWidgets.QWidget()
        self.tabParameters.setObjectName("tabParameters")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabParameters)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabInner = QtWidgets.QTabWidget(self.tabParameters)
        self.tabInner.setObjectName("tabInner")
        self.tabSubcatchments = QtWidgets.QWidget()
        self.tabSubcatchments.setObjectName("tabSubcatchments")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabSubcatchments)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listSubcatchments = QtWidgets.QListWidget(self.tabSubcatchments)
        self.listSubcatchments.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listSubcatchments.setObjectName("listSubcatchments")
        self.horizontalLayout_4.addWidget(self.listSubcatchments)
        self.widget = QtWidgets.QWidget(self.tabSubcatchments)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout.addWidget(self.widget_3)
        self.horizontalLayout_4.addWidget(self.widget)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabInner.addTab(self.tabSubcatchments, "")
        self.tabLID_Controls = QtWidgets.QWidget()
        self.tabLID_Controls.setObjectName("tabLID_Controls")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tabLID_Controls)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listLID_Controls = QtWidgets.QListWidget(self.tabLID_Controls)
        self.listLID_Controls.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listLID_Controls.setObjectName("listLID_Controls")
        self.horizontalLayout_2.addWidget(self.listLID_Controls)
        self.widget_2 = QtWidgets.QWidget(self.tabLID_Controls)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.tabInner.addTab(self.tabLID_Controls, "")
        self.verticalLayout_2.addWidget(self.tabInner)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(self.tabParameters)
        self.widget_4.setMinimumSize(QtCore.QSize(600, 0))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout.addWidget(self.widget_4)
        self.buttonOkParameters = QtWidgets.QPushButton(self.tabParameters)
        self.buttonOkParameters.setMaximumSize(QtCore.QSize(100, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/21828-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonOkParameters.setIcon(icon1)
        self.buttonOkParameters.setCheckable(False)
        self.buttonOkParameters.setChecked(False)
        self.buttonOkParameters.setAutoDefault(False)
        self.buttonOkParameters.setDefault(True)
        self.buttonOkParameters.setObjectName("buttonOkParameters")
        self.horizontalLayout.addWidget(self.buttonOkParameters)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabOuter.addTab(self.tabParameters, "")
        self.tabObservations = QtWidgets.QWidget()
        self.tabObservations.setObjectName("tabObservations")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabObservations)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.tabObservations)
        self.label.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(75, -1, 75, -1)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButtonTotalEvap = QtWidgets.QPushButton(self.tabObservations)
        self.pushButtonTotalEvap.setObjectName("pushButtonTotalEvap")
        self.verticalLayout_4.addWidget(self.pushButtonTotalEvap)
        self.pushButtonSurfInfil = QtWidgets.QPushButton(self.tabObservations)
        self.pushButtonSurfInfil.setObjectName("pushButtonSurfInfil")
        self.verticalLayout_4.addWidget(self.pushButtonSurfInfil)
        self.pushButtonSoilPerc = QtWidgets.QPushButton(self.tabObservations)
        self.pushButtonSoilPerc.setObjectName("pushButtonSoilPerc")
        self.verticalLayout_4.addWidget(self.pushButtonSoilPerc)
        self.pushButtonBottomInfil = QtWidgets.QPushButton(self.tabObservations)
        self.pushButtonBottomInfil.setObjectName("pushButtonBottomInfil")
        self.verticalLayout_4.addWidget(self.pushButtonBottomInfil)
        self.pushButtonSurfRunoff = QtWidgets.QPushButton(self.tabObservations)
        self.pushButtonSurfRunoff.setObjectName("pushButtonSurfRunoff")
        self.verticalLayout_4.addWidget(self.pushButtonSurfRunoff)
        self.pushButtonDrainOut = QtWidgets.QPushButton(self.tabObservations)
        self.pushButtonDrainOut.setObjectName("pushButtonDrainOut")
        self.verticalLayout_4.addWidget(self.pushButtonDrainOut)
        self.pushButtonSurfDepth = QtWidgets.QPushButton(self.tabObservations)
        self.pushButtonSurfDepth.setObjectName("pushButtonSurfDepth")
        self.verticalLayout_4.addWidget(self.pushButtonSurfDepth)
        self.pushButtonSoilMoist = QtWidgets.QPushButton(self.tabObservations)
        self.pushButtonSoilMoist.setObjectName("pushButtonSoilMoist")
        self.verticalLayout_4.addWidget(self.pushButtonSoilMoist)
        self.pushButtonStorageDepth = QtWidgets.QPushButton(self.tabObservations)
        self.pushButtonStorageDepth.setObjectName("pushButtonStorageDepth")
        self.verticalLayout_4.addWidget(self.pushButtonStorageDepth)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.tabOuter.addTab(self.tabObservations, "")
        self.tabControls = QtWidgets.QWidget()
        self.tabControls.setObjectName("tabControls")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tabControls)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_5 = QtWidgets.QWidget(self.tabControls)
        self.widget_5.setMinimumSize(QtCore.QSize(325, 0))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7.addWidget(self.widget_5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_7 = QtWidgets.QWidget(self.tabControls)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 175))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5.addWidget(self.widget_7)
        self.pushButtonRunPEST = QtWidgets.QPushButton(self.tabControls)
        self.pushButtonRunPEST.setMinimumSize(QtCore.QSize(65, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButtonRunPEST.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Images/Go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRunPEST.setIcon(icon2)
        self.pushButtonRunPEST.setDefault(True)
        self.pushButtonRunPEST.setObjectName("pushButtonRunPEST")
        self.verticalLayout_5.addWidget(self.pushButtonRunPEST)
        self.labelLoading = QtWidgets.QLabel(self.tabControls)
        self.labelLoading.setText("")
        self.labelLoading.setObjectName("labelLoading")
        self.verticalLayout_5.addWidget(self.labelLoading)
        self.widget_8 = QtWidgets.QWidget(self.tabControls)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5.addWidget(self.widget_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.widget_6 = QtWidgets.QWidget(self.tabControls)
        self.widget_6.setMinimumSize(QtCore.QSize(325, 0))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_7.addWidget(self.widget_6)
        self.tabOuter.addTab(self.tabControls, "")
        self.gridLayout.addWidget(self.tabOuter, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 771, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabOuter.setCurrentIndex(0)
        self.tabInner.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SWMM2PEST"))
        self.tabInner.setTabText(self.tabInner.indexOf(self.tabSubcatchments), _translate("MainWindow", "Subcatchments"))
        self.tabInner.setTabText(self.tabInner.indexOf(self.tabLID_Controls), _translate("MainWindow", "LID_Controls"))
        self.buttonOkParameters.setText(_translate("MainWindow", "Next"))
        self.tabOuter.setTabText(self.tabOuter.indexOf(self.tabParameters), _translate("MainWindow", "Parameter Data"))
        self.label.setText(_translate("MainWindow", "        Select Output Parameter:"))
        self.pushButtonTotalEvap.setText(_translate("MainWindow", "Total Evaporation"))
        self.pushButtonSurfInfil.setText(_translate("MainWindow", "Surface Infiltration"))
        self.pushButtonSoilPerc.setText(_translate("MainWindow", "Soil Perc"))
        self.pushButtonBottomInfil.setText(_translate("MainWindow", "Bottom Infiltration"))
        self.pushButtonSurfRunoff.setText(_translate("MainWindow", "Surface Runoff"))
        self.pushButtonDrainOut.setText(_translate("MainWindow", "Drain Outflow"))
        self.pushButtonSurfDepth.setText(_translate("MainWindow", "Surface Depth"))
        self.pushButtonSoilMoist.setText(_translate("MainWindow", "Soil/Pave Moist"))
        self.pushButtonStorageDepth.setText(_translate("MainWindow", "Storage Depth"))
        self.tabOuter.setTabText(self.tabOuter.indexOf(self.tabObservations), _translate("MainWindow", "Observation Data"))
        self.pushButtonRunPEST.setText(_translate("MainWindow", " Run"))
        self.tabOuter.setTabText(self.tabOuter.indexOf(self.tabControls), _translate("MainWindow", "Control Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

